local ps = "\n\nP.S. This letter was generated by a Lua script."

-- "a" mode: append
local file = io.open("letter.txt", "a")

if file then
    file:write(ps)
    file:close()
    print("P.S. appended to the file.")
else
    print("Could not append.")
end
